
######uuid使用libevent生成######
set(UUID_EXTERNAL_COMPILER_FLAGS
        URL ${UUID_URL}
        URL_HASH MD5=${UUID_URL_HASH}
        CONFIGURE_COMMAND ./configure CFLAGS=-fPIC --prefix=<INSTALL_DIR>
        BUILD_IN_SOURCE 1
        BUILD_COMMAND ${MAKE}
        )
option(UUID_ENABLE "Enable Uuid." ON)

set(OPUS_EXTERNAL_COMPILER_FLAGS
        URL ${OPUS_URL}
        URL_HASH MD5=${OPUS_URL_HASH}
        CONFIGURE_COMMAND ./configure CFLAGS=-fPIC  --prefix=<INSTALL_DIR>
        BUILD_IN_SOURCE 1
        BUILD_COMMAND ${MAKE}
        )
option(OPUS_ENABLE "Enable Opus." ON)

set(OPENSSL_EXTERNAL_COMPILER_FLAGS
        URL ${OPENSSL_URL}
        URL_HASH MD5=${OPENSSL_URL_HASH}
        CONFIGURE_COMMAND ./config -fPIC --prefix=<INSTALL_DIR>
        BUILD_IN_SOURCE 1
        BUILD_COMMAND ${MAKE}
        )
option(OPENSSL_ENABLE "Enable Openssl." ON)

set(LOG4CPP_EXTERNAL_COMPILER_FLAGS
        URL ${LOG4CPP_URL}
        URL_HASH MD5=${LOG4CPP_URL_HASH}
        CONFIGURE_COMMAND  ./configure CXXFLAGS=-fPIC  --prefix=<INSTALL_DIR>
        BUILD_IN_SOURCE 1
        BUILD_COMMAND ${MAKE}
        )
option(LOG4CPP_ENABLE "Enable Log4Cpp." ON)

set(LIBEVENT_EXTERNAL_COMPILER_FLAGS
        URL ${LIBEVENT_URL}
        URL_HASH MD5=${LIBEVENT_URL_HASH}
        CONFIGURE_COMMAND ./configure CFLAGS=-fPIC  --prefix=<INSTALL_DIR>
        BUILD_IN_SOURCE 1
        BUILD_COMMAND ${MAKE}
        )
option(LIBEVENT_ENABLE "Enable Libevent." ON)

set(JSONCPP_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")
set(JSONCPP_EXTERNAL_COMPILER_FLAGS
        URL ${JSONCPP_URL}
        URL_HASH MD5=${JSONCPP_URL_HASH}
        CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
        -DCMAKE_CXX_FLAGS=${JSONCPP_CXX_FLAGS}
        -DJSONCPP_WITH_TESTS=OFF
        -DJSONCPP_WITH_POST_BUILD_UNITTEST=OFF
        -DJSONCPP_WITH_WARNING_AS_ERROR=OFF
        -DJSONCPP_WITH_PKGCONFIG_SUPPORT=OFF
        -DJSONCPP_WITH_CMAKE_PACKAGE=OFF
        -DBUILD_SHARED_LIBS=ON
        -DBUILD_STATIC_LIBS=ON
        )
option(JSONCPP_ENABLE "Enable Jsoncpp." ON)

set(GTEST_EXTERNAL_COMPILER_FLAGS
        URL ${GTEST_URL}
        URL_HASH MD5=${GTEST_URL_HASH}
        CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
        -DBUILD_SHARED_LIBS=ON
        -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
        -Dgtest_build_tests=OFF
        -Dgmock_build_tests=OFF
        )
option(GTEST_ENABLE "Enable Gtest." ON)
