/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alibaba_nls_client_util_OpuCodec */

#ifndef _Included_com_alibaba_nls_client_util_OpuCodec
#define _Included_com_alibaba_nls_client_util_OpuCodec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alibaba_nls_client_util_OpuCodec
 * Method:    createOpuEncoder
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_alibaba_nls_client_util_OpuCodec_createOpuEncoder
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_alibaba_nls_client_util_OpuCodec
 * Method:    encode
 * Signature: (J[BI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_alibaba_nls_client_util_OpuCodec_encode
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_alibaba_nls_client_util_OpuCodec
 * Method:    destroyOpuEncoder
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_alibaba_nls_client_util_OpuCodec_destroyOpuEncoder
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
